const product_data = [
  {
    id: 1,
    name: "Product 1",
    description: "Description for Product 1.",
    price: 19.99,
    image: "image/rice.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 2,
    name: "Product 2",
    description: "Description for Product 2.",
    price: 29.99,
    image: "image/agree_03.jpg",
    style_h: 40,
    style_w: 20,
    link: "/services",
  },
  {
    id: 3,
    name: "Product 3",
    description: "Description for Product 3.",
    price: 29.99,
    image: "image/Atta_01.jpg",
    style_h: 40,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/dal_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/chola_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/bajra_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/millets_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/mustard_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/dal_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/chola_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/bajra_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/millets_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description for Product 4.",
    price: 29.99,
    image: "image/mustard_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/services",
  },
];

export default product_data;
